---
- name: 'Copy gitlab RPM'
  hosts: 'all'
  gather_facts: true
  become: true

  tasks:

    - name: Create folder /var/cache/zypp/packages/gitlab-ce/
      ansible.builtin.file:
        path: '/var/cache/zypp/packages/gitlab-ce/'
        state: 'directory'
        owner: 'root'
        group: 'root'
        mode: '0755'

    - name: 'Copy gitlab RPM'
      ansible.builtin.copy:
        src: "{{ lookup('ansible.builtin.fileglob', '*.rpm') }}"
        dest: "/var/cache/zypp/packages/gitlab-ce/"
