---

- name: 'Run playbook-all_nodes-set_hostname.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-set_hostname.yml

- name: 'Run playbook-all_nodes-minimal_bashrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_bashrc.yml

- name: 'Run 10_SLES_register.yml'
  ansible.builtin.import_playbook: 10_SLES_register.yml

- name: 'Run playbook-all_nodes-zypper_ref_accept_keys.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-zypper_ref_accept_keys.yml

- name: 'Run playbook-all_nodes-minimal_tmux_configuration.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_tmux_configuration.yml

- name: 'Run playbook-all_nodes-install_git.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-install_git.yml

- name: 'Run playbook-all_nodes-install_hostname.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-install_hostname.yml

- name: 'Run playbook-all_nodes-copy_gitlab_RPM.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-copy_gitlab_RPM.yml

- name: 'Run playbook-all_nodes-add_gitlab-ce_repository.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-add_gitlab-ce_repository.yml

- name: 'Run playbook-all_nodes-alvistack.gitlab_ce.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-alvistack.gitlab_ce.yml
